#!/usr/bin/env python

import sys
import os 
from selenium import webdriver

path = "/home/kxn/Repos/"
browser = webdriver.Chrome()
browser.get('http://github.com/login')

username = os.environ['GITHUBUN'] 
password = os.environ['GITHUBPW'] 

def create():
    folderName = str(sys.argv[1])
    os.makedirs(path + folderName)
    python_button = browser.find_elements_by_xpath("//input[@name='login']")[0]
    python_button.send_keys(username) 
    python_button = browser.find_elements_by_xpath("//input[@name='password']")[0] 
    python_button.send_keys(password)
    python_button = browser.find_elements_by_xpath("//input[@name='commit']")[0]
    python_button.click()
    browser.get('https://github.com/new') 
    python_button = browser.find_elements_by_xpath("//input[@name='repository[name]']")[0] 
    python_button.send_keys(folderName)
    python_button = browser.find_element_by_css_selector('button.first-in-line')
    python_button.submit()
    browser.quit()

    os.chdir(path + folderName)
    os.system('echo "# ' + folderName + ' " >> README.md')
    os.system('git init')
    os.system('git add README.md')
    os.system('git commit -m "first commit"')
    os.system('git remote add origin git@github.com:kxnaylorCLE216/' + folderName)
    os.system('git push -u origin master')
    os.system('code .')


if __name__ == "__main__":
    create()
